Update sites.html
CelestiaProject/www pull request #33
Opened 2022-09-26 00:59 UTC by Anthony-B-Russo10

Update sites.html to include more help Celestia Links.

2022-09-26 08:43 UTC, 375gnu commented
only the site and the forum are "official" resources. i don't think it's a good idea to list all 3rd party resources here.

2022-09-26 11:27 UTC, TheLostProbe commented
im unsure on the celestia.mobi source code one. but most, if not all the others should be kept, especially the wikibooks since it is good for first-timers and people looking to troubleshoot. social platforms such as the subreddit and the discord should probably also be kept since some people may not know how to use the forums, and response times on discord are much faster because it is real-time. the archive repository is good for people looking for old versions of celestia, since the sourceforge is now practically obsolete

2022-09-26 11:30 UTC, levinli303 commented
the celestia.mobi repository does not contain critical source code (it only has css stylesheets and some redirection links) so it is unnecessary to put it up there.

2022-09-26 16:31 UTC, Anthony-B-Russo10 commented
I mainly put the celestia.mobi repository there due to that being where the addon submissions are sent for celestia.mobi's addons section though if need be I'll change the link to go to the repository's Issues tab.

2022-09-27 02:48 UTC, levinli303 commented
we can just put https://celestia.mobi since the front page has a link to submission.

2022-09-27 06:25 UTC, 375gnu commented
I'm okay with https://celestia.mobi/ addition, but not other resources

2022-09-27 07:39 UTC, 375gnu commented
agree with wikibooks.

2022-09-27 22:35 UTC, Anthony-B-Russo10 commented
Updated to change Mobi's link to the main page.

> i think reddit and discord links should be added to the footer alongside the twitter, github, and email, instead of in sites.html.

Those would also need to be updated to all the html files for the site, but yeah that would be a better place for those.

2022-09-27 23:39 UTC, TheLostProbe commented
problem is that i dont know where the icon files for the footer links are stored. im guessing they are stored somewhere else on the server and not in the websites files itself, or perhaps they were not added to the github repository

2022-09-27 23:55 UTC, Anthony-B-Russo10 commented
I think they are all stored on the server side of the site, but what is odd is that I can't even find the icons when doing an inspect element on the site as well.

2022-09-28 08:08 UTC, 375gnu requested changes

2022-09-28 08:08 UTC, 375gnu commented on sites.html
> +					<li><b><a href="https://discord.com/invite/WEWDcJh" target="_blank">Celestia Official Discord Server</a></b><br>
remove this

2022-09-28 08:08 UTC, 375gnu commented on sites.html
> +					<li><b><a href="https://www.reddit.com/r/Celestiasoftware/" target="_blank">Celestia Official Subreddit</a></b><br>
remove this

2022-09-28 08:08 UTC, 375gnu commented on sites.html
> +					<li><b><a href="https://github.com/Anthony-B-Russo10/Celestia-Archive" target="_blank">Celestia Archive GitHub Repository</a></b><br>
remove this

2022-09-28 08:08 UTC, 375gnu commented on sites.html
> +                                	Celestia.mobi main site with links to downloads of the mobile versions of Celestia along with hosted addons.
plz change to "Celestia for mobile devices"

2022-09-28 17:27 UTC, Anthony-B-Russo10 commented
Changes performed.

2022-09-28 18:17 UTC, 375gnu requested changes
please squash commits

2022-09-28 18:40 UTC, Anthony-B-Russo10 commented
One problem, Github won't let me squash the commits.
![image](https://user-images.githubusercontent.com/57239744/192862727-90981021-1eba-4065-94e7-293a0637eed2.png)

2022-09-28 18:57 UTC, Anthony-B-Russo10 commented
Commits squashed.

2022-09-29 07:56 UTC, 375gnu commented
There are still 4 commits instead of 1.

2022-09-29 19:10 UTC, Anthony-B-Russo10 commented
Squashed

2022-09-29 19:15 UTC, 375gnu commented
![image](https://user-images.githubusercontent.com/1612688/193122335-5fa1cb37-8e2a-4f7a-8129-1cd82581aff2.png)

2022-09-29 22:19 UTC, Anthony-B-Russo10 commented
One problem.
![image](https://user-images.githubusercontent.com/57239744/193152291-c5db7d28-8aae-44fa-a8d2-9d81a646934a.png)

2022-09-30 05:35 UTC, TheLostProbe commented
you should be able to do this much easier through github desktop or using git

2022-09-30 09:35 UTC, Anthony-B-Russo10 commented
Only way I figured out how to do it was on GitHub desktop and even that doesn't want to do it now.

2022-09-30 10:19 UTC, 375gnu commented
git rebase -i master

2022-09-30 23:42 UTC, Anthony-B-Russo10 commented
This leads to problem number two, I have never used GitHub via command line.

2022-10-01 09:25 UTC, 375gnu commented
git push -f

2022-10-01 21:23 UTC, Anthony-B-Russo10 commented
That still doesn't work.
![image](https://user-images.githubusercontent.com/57239744/193428826-ad447f36-e224-4a31-983a-95631ecc8b3c.png)

2022-10-01 21:31 UTC, 375gnu commented
git remote set-url git@github.com:CelestiaProject/www.git

and upload your ssh key to gh account

2022-10-01 22:25 UTC, Anthony-B-Russo10 commented
The SSH key I uploaded last night, that didn't do much to help.
And:
![image](https://user-images.githubusercontent.com/57239744/193430492-e18db77c-d4da-4306-80a7-841f3a114d38.png)

2022-10-02 11:03 UTC, 375gnu commented
git remote set-url origin git@github.com:CelestiaProject/www.git

2022-10-02 21:41 UTC, Anthony-B-Russo10 commented
I got it down to two commits, I can not get it any lower as not Git will not connect to the origin. The only way this is getting down to one commit is by creating a new pull request with the same changes.

2022-10-03 08:15 UTC, 375gnu commented
please create a new PR then

2022-10-03 08:15 UTC, closed without merging